### ISSUE TITLE
How Do I Become a World Class Blockstack Evangelist?

### ISSUE THREAD

**Issue by dantrevino** [blockstack/evangelists#2]
Submitted for feedback.

# How Do I Become a World Class Blockstack Evangelist?

**What is a Blockstack evangelist?**
A Blockstack evangelist is:
 - An individual who is passionate about the Blockstack platform and ideals
 - Willing to share with fellow evangelists
 - Part product marketer, part developer/tinkerer, maybe both 

**What are the product areas that I should learn to become a Blockstack expert?**  Based on my current understanding, I would break it down this way below.  

Currently, I see the 3 pillars of the Blockstack platform as:
([whitepaper link](https://blockstack.org/whitepaper.pdf))

1. Decentralized Identity
2. Decentralized Storage (Gaia)
3. Discovery/Replication (Atlas)

In addtion, there are several other key components that are important.  Below are the areas of knowledge required, with some component pieces identified.

**System Architecture**  
1. Component Architecture ( [forum link](https://forum.blockstack.org/t/component-architecture/1417)) & Blockstack layers (ref: whitepaper)
2. Blockstack Core API 
4. Full Node vs Light Client
5. Virtual Chains and their implementation
6. Blockstack Browser
7. Architeture Roadmap

**Decentralized Identity**
1. Overview - BNS and it's operation, zone files
2. Authorization - Concepts, APIs
3. Domains/Subdomains
4. Replication
5. Discoverability
6. Identity Roadmap

**Decentralized Storage (Gaia)**
1. Basics - Storage Layers, basic file operations
2. Multi-Reader data access
3. Multi-Device data access
4. Driver API
5. Storage Roadmap

**Discovery/Replication (Atlas)**
1. Concepts
2. Full Node
3. Roadmap

**Comment by jackzampolin** [comment]
Dan I love this! Going to move it into it's own file and add some more links here!

**Comment by jackzampolin** [comment]
Added this to the readme! Closing this. If you would like more done here please open more issues!
